import type { Category, Product } from '@/types';

export const categories: Category[] = [
  {
    slug: 'seragam-sekolah',
    name: 'Seragam Sekolah',
    description:
      'Seragam siswa dan siswi dengan bahan nyaman, tahan lama, dan sesuai standar sekolah.',
    image:
      'https://images.pexels.com/photos/8617715/pexels-photo-8617715.jpeg?auto=compress&cs=tinysrgb&w=1200',
    icon: 'GraduationCap',
    productCount: 12,
  },
  {
    slug: 'seragam-perusahaan',
    name: 'Seragam Perusahaan',
    description:
      'Seragam kerja profesional yang merepresentasikan identitas brand perusahaan Anda.',
    image:
      'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=1200',
    icon: 'Building2',
    productCount: 9,
  },
  {
    slug: 'kaos-custom',
    name: 'Kaos Custom',
    description:
      'Kaos sablon custom dengan teknik sablon premium dan bahan katun combed berkualitas.',
    image:
      'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=1200',
    icon: 'Shirt',
    productCount: 15,
  },
  {
    slug: 'polo-shirt',
    name: 'Polo Shirt',
    description:
      'Polo shirt premium dengan bordir logo atau sablon untuk seragam kerja dan komunitas.',
    image:
      'https://images.pexels.com/photos/3622608/pexels-photo-3622608.jpeg?auto=compress&cs=tinysrgb&w=1200',
    icon: 'Shirt',
    productCount: 10,
  },
  {
    slug: 'wearpack',
    name: 'Wearpack',
    description:
      'Wearpack industri dan lapangan dengan bahan ripstop yang kuat, aman, dan nyaman dipakai.',
    image:
      'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=1200',
    icon: 'HardHat',
    productCount: 8,
  },
  {
    slug: 'jaket',
    name: 'Jaket',
    description:
      'Jaket varsity, bomber, dan almamater premium dengan bahan berkualitas dan bordir kustom.',
    image:
      'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=1200',
    icon: 'Wind',
    productCount: 7,
  },
  {
    slug: 'bahan-kain',
    name: 'Bahan Kain',
    description:
      'Aneka bahan kain grade A: katun combed, drill, polyester, dan lainnya dengan harga grosir.',
    image:
      'https://images.pexels.com/photos/6809657/pexels-photo-6809657.jpeg?auto=compress&cs=tinysrgb&w=1200',
    icon: 'Layers',
    productCount: 20,
  },
  {
    slug: 'atribut-sekolah',
    name: 'Atribut Sekolah',
    description:
      'Dasi, topi, dompet, tali nama, sabuk, dan atribut sekolah lengkap dengan kualitas terjamin.',
    image:
      'https://images.pexels.com/photos/289737/pexels-photo-289737.jpeg?auto=compress&cs=tinysrgb&w=1200',
    icon: 'Star',
    productCount: 18,
  },
];

export const products: Product[] = [
  // ─── SERAGAM SEKOLAH ───────────────────────────────────────────────────────
  {
    slug: 'seragam-sekolah-standar',
    name: 'Seragam Sekolah Standar',
    category: 'seragam-sekolah',
    categoryLabel: 'Seragam Sekolah',
    shortDescription: 'Seragam siswa lengkap dengan bahan adem dan jahitan rapi.',
    description:
      'Seragam sekolah standar dengan bahan katun twill premium yang adem, tidak menerawang, dan tahan lama. Jahitan rantai di area kritikal memastikan ketahanan saat dicuci berulang. Tersedia untuk SD, SMP, dan SMA dengan warna sesuai standar sekolah.',
    images: [
      'https://images.pexels.com/photos/8617715/pexels-photo-8617715.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/8617742/pexels-photo-8617742.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/8617711/pexels-photo-8617711.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/8617743/pexels-photo-8617743.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 65000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 65000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 55000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 48000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Merah Maroon', hex: '#7f1d1d' },
      { name: 'Abu', hex: '#64748b' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviewCount: 128,
    badge: 'Best Seller',
    features: [
      'Bahan katun twill premium, adem dan tidak menerawang',
      'Jahitan rantai di area kritikal untuk ketahanan ekstra',
      'Tersedia warna sesuai standar sekolah',
      'Bordir nama sekolah gratis (min. 50 pcs)',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Katun Twill 30s' },
      { label: 'Tebal Kain', value: '180–200 gsm' },
      { label: 'Teknik Bordir', value: 'Computerized Embroidery' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '7–10 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },
  {
    slug: 'seragam-olahraga-sekolah',
    name: 'Seragam Olahraga Sekolah',
    category: 'seragam-sekolah',
    categoryLabel: 'Seragam Sekolah',
    shortDescription: 'Baju olahraga sekolah bahan drifit breathable, anti keringat.',
    description:
      'Seragam olahraga sekolah dengan bahan drifit polyester yang menyerap keringat cepat, ringan, dan nyaman dipakai aktivitas tinggi. Sablon nama sekolah dan logo dengan teknik heat transfer premium. Tersedia untuk SD, SMP, dan SMA.',
    images: [
      'https://images.pexels.com/photos/3621104/pexels-photo-3621104.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/2827400/pexels-photo-2827400.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3621175/pexels-photo-3621175.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3621104/pexels-photo-3621104.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 55000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 55000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 47000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 40000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Merah', hex: '#dc2626' },
      { name: 'Hijau', hex: '#16a34a' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 94,
    badge: 'Populer',
    features: [
      'Bahan drifit polyester, menyerap keringat cepat',
      'Ringan dan elastis untuk aktivitas tinggi',
      'Sablon heat transfer tahan lama',
      'Jahitan flatlock yang nyaman di kulit',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Drifit Polyester' },
      { label: 'Tebal Kain', value: '140–160 gsm' },
      { label: 'Teknik Sablon', value: 'Heat Transfer' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },
  {
    slug: 'rok-sekolah',
    name: 'Rok Sekolah Plisket & Polos',
    category: 'seragam-sekolah',
    categoryLabel: 'Seragam Sekolah',
    shortDescription: 'Rok sekolah plisket dan polos untuk SD, SMP, SMA berkualitas.',
    description:
      'Rok sekolah tersedia model plisket dan polos dengan bahan serge berkualitas yang jatuh sempurna, tidak mudah kusut, dan tahan lama. Tersedia berbagai ukuran dari anak-anak hingga dewasa sesuai standar sekolah.',
    images: [
      'https://images.pexels.com/photos/8617715/pexels-photo-8617715.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/8617742/pexels-photo-8617742.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/289737/pexels-photo-289737.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/8617711/pexels-photo-8617711.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 45000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 45000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 38000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 32000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Abu', hex: '#64748b' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Putih', hex: '#f8fafc' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 72,
    features: [
      'Bahan serge premium, jatuh sempurna',
      'Tidak mudah kusut dan tahan lama',
      'Tersedia model plisket dan polos',
      'Tersedia ukuran anak hingga dewasa',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Serge Premium' },
      { label: 'Model', value: 'Plisket / Polos' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },

  // ─── SERAGAM PERUSAHAAN ────────────────────────────────────────────────────
  {
    slug: 'seragam-perusahaan-polo',
    name: 'Seragam Perusahaan Polo',
    category: 'seragam-perusahaan',
    categoryLabel: 'Seragam Perusahaan',
    shortDescription: 'Polo shirt premium dengan bordir logo perusahaan.',
    description:
      'Polo shirt seragam perusahaan dengan bahan lacoste pique yang breathable dan tahan kusut. Bordir logo perusahaan dengan teknik computerized embroidery menghasilkan detail tajam dan tahan lama. Cocok untuk staff, sales, dan event perusahaan.',
    images: [
      'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3622608/pexels-photo-3622608.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3184325/pexels-photo-3184325.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 85000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 85000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 75000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 68000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Maroon', hex: '#7f1d1d' },
      { name: 'Forest', hex: '#14532d' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 86,
    badge: 'Premium',
    features: [
      'Bahan lacoste pique 30s, breathable dan tahan kusut',
      'Bordir logo computerized dengan detail tajam',
      'Kerah dan manset double needle untuk ketahanan',
      'Tersedia 15+ warna pilihan',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Lacoste Pique 30s' },
      { label: 'Tebal Kain', value: '200–220 gsm' },
      { label: 'Teknik Logo', value: 'Computerized Embroidery' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '7–10 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },
  {
    slug: 'kemeja-seragam-perusahaan',
    name: 'Kemeja Seragam Perusahaan',
    category: 'seragam-perusahaan',
    categoryLabel: 'Seragam Perusahaan',
    shortDescription: 'Kemeja seragam formal kantor dengan bordir logo profesional.',
    description:
      'Kemeja seragam perusahaan dengan bahan katun CVC yang tidak mudah kusut dan nyaman dipakai seharian. Model lengan panjang dan pendek tersedia. Bordir logo di dada kiri dengan teknik computerized untuk tampilan profesional.',
    images: [
      'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3184325/pexels-photo-3184325.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 90000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 90000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 80000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 72000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Biru Muda', hex: '#bfdbfe' },
      { name: 'Cream', hex: '#fef9c3' },
      { name: 'Abu Muda', hex: '#e2e8f0' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviewCount: 61,
    badge: 'Populer',
    features: [
      'Bahan katun CVC, tidak mudah kusut',
      'Model lengan panjang & pendek tersedia',
      'Bordir logo dada kiri',
      'Finishing rapi dan profesional',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Katun CVC 40s' },
      { label: 'Tebal Kain', value: '120–140 gsm' },
      { label: 'Teknik Logo', value: 'Computerized Embroidery' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '7–10 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },

  // ─── KAOS CUSTOM ──────────────────────────────────────────────────────────
  {
    slug: 'kaos-custom-combed',
    name: 'Kaos Custom Combed 30s',
    category: 'kaos-custom',
    categoryLabel: 'Kaos Custom',
    shortDescription: 'Kaos sablon custom bahan katun combed 30s premium.',
    description:
      'Kaos custom dengan bahan katun combed 30s yang lembut, adem, dan jatuh sempurna. Sablon menggunakan tinta plastisol / waterbased yang aman dan tahan lama. Cocok untuk event, komunitas, merchandise, dan promo.',
    images: [
      'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/1656684/pexels-photo-1656684.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/6311392/pexels-photo-6311392.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 45000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 45000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 38000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 32000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Maroon', hex: '#7f1d1d' },
      { name: 'Olive', hex: '#3f6212' },
      { name: 'Mustard', hex: '#c9a84c' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviewCount: 215,
    badge: 'Populer',
    features: [
      'Bahan katun combed 30s, lembut dan adem',
      'Sablon plastisol / waterbased tahan lama',
      'Jahitan rantai di bahu dan ketiak',
      'Gratis desain artwork',
      'Quality control sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Katun Combed 30s' },
      { label: 'Tebal Kain', value: '180 gsm' },
      { label: 'Teknik Sablon', value: 'Plastisol / Waterbased' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },
  {
    slug: 'kaos-oversize-custom',
    name: 'Kaos Oversize Custom',
    category: 'kaos-custom',
    categoryLabel: 'Kaos Custom',
    shortDescription: 'Kaos oversize custom bahan cotton bamboo premium untuk streetwear.',
    description:
      'Kaos oversize dengan bahan cotton bamboo yang lembut, adem, dan jatuh bagus untuk tampilan streetwear kekinian. Sablon DTF (Direct To Film) full color dengan detail tinggi. Cocok untuk brand clothing, merchandise komunitas, dan event.',
    images: [
      'https://images.pexels.com/photos/1656684/pexels-photo-1656684.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/6311392/pexels-photo-6311392.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 55000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 55000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 47000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 40000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Sand', hex: '#d2b48c' },
      { name: 'Sage', hex: '#7fa98a' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviewCount: 143,
    badge: 'Trending',
    features: [
      'Bahan cotton bamboo, lembut dan adem',
      'Sablon DTF full color detail tinggi',
      'Potongan oversize trendi',
      'Gratis desain artwork',
      'Quality control sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Cotton Bamboo' },
      { label: 'Tebal Kain', value: '200 gsm' },
      { label: 'Teknik Sablon', value: 'DTF (Direct To Film)' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },

  // ─── POLO SHIRT ───────────────────────────────────────────────────────────
  {
    slug: 'polo-shirt-lacoste',
    name: 'Polo Shirt Lacoste Pique',
    category: 'polo-shirt',
    categoryLabel: 'Polo Shirt',
    shortDescription: 'Polo shirt lacoste pique premium dengan bordir logo kustom.',
    description:
      'Polo shirt dengan bahan lacoste pique grade A yang breathable, tahan kusut, dan nyaman dipakai seharian. Bordir logo dengan computerized embroidery menghasilkan detail yang tajam. Cocok untuk seragam kerja, komunitas, dan event.',
    images: [
      'https://images.pexels.com/photos/3622608/pexels-photo-3622608.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 80000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 80000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 70000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 62000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Merah', hex: '#dc2626' },
      { name: 'Abu', hex: '#64748b' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviewCount: 177,
    badge: 'Best Seller',
    features: [
      'Bahan lacoste pique grade A, breathable',
      'Bordir logo computerized detail tajam',
      'Kerah dan manset ribbed berkualitas',
      'Tersedia 20+ pilihan warna',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Lacoste Pique Grade A' },
      { label: 'Tebal Kain', value: '200–220 gsm' },
      { label: 'Teknik Logo', value: 'Computerized Embroidery' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '7–10 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },
  {
    slug: 'polo-shirt-drifit',
    name: 'Polo Shirt Drifit Sport',
    category: 'polo-shirt',
    categoryLabel: 'Polo Shirt',
    shortDescription: 'Polo shirt drifit sporty untuk olahraga dan aktivitas lapangan.',
    description:
      'Polo shirt drifit dengan bahan polyester microfiber yang ringan, menyerap keringat, dan cepat kering. Cocok untuk seragam olahraga, kepanitiaan, event outdoor, dan aktivitas lapangan. Tersedia dengan opsi sablon atau bordir.',
    images: [
      'https://images.pexels.com/photos/3621104/pexels-photo-3621104.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3622608/pexels-photo-3622608.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/2827400/pexels-photo-2827400.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3621175/pexels-photo-3621175.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 65000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 65000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 57000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 50000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Merah', hex: '#dc2626' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.7,
    reviewCount: 88,
    features: [
      'Bahan drifit polyester microfiber',
      'Menyerap keringat dan cepat kering',
      'Cocok untuk aktivitas outdoor',
      'Pilihan sablon atau bordir',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Polyester Microfiber Drifit' },
      { label: 'Tebal Kain', value: '150–170 gsm' },
      { label: 'Teknik Logo', value: 'Sablon / Bordir' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },

  // ─── WEARPACK ─────────────────────────────────────────────────────────────
  {
    slug: 'wearpack-industri',
    name: 'Wearpack Industri Ripstop',
    category: 'wearpack',
    categoryLabel: 'Wearpack',
    shortDescription: 'Wearpack industri bahan ripstop kuat dan tahan abrasi untuk kerja lapangan.',
    description:
      'Wearpack industri dengan bahan ripstop yang kuat, tahan abrasi, dan nyaman dipakai di lingkungan kerja berat. Jahitan dobel di area tekanan tinggi. Dilengkapi banyak kantong fungsional. Cocok untuk industri manufaktur, tambang, dan konstruksi.',
    images: [
      'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3862601/pexels-photo-3862601.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3862601/pexels-photo-3862601.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 185000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 185000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 165000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 148000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Abu Tua', hex: '#334155' },
      { name: 'Jingga', hex: '#ea580c' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 52,
    badge: 'Premium',
    features: [
      'Bahan ripstop, kuat dan tahan abrasi',
      'Jahitan dobel di area tekanan tinggi',
      'Multi kantong fungsional',
      'Bordir nama/logo perusahaan',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Ripstop 240 gsm' },
      { label: 'Jahitan', value: 'Double Stitch' },
      { label: 'Teknik Logo', value: 'Computerized Embroidery' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '10–14 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },
  {
    slug: 'wearpack-mekanik',
    name: 'Wearpack Mekanik Coverall',
    category: 'wearpack',
    categoryLabel: 'Wearpack',
    shortDescription: 'Coverall mekanik satu bagian dengan bahan canvas berkualitas.',
    description:
      'Wearpack model coverall satu bagian untuk mekanik dan teknisi dengan bahan canvas yang tebal dan tahan lama. Resleting YKK berkualitas, kantong banyak dan fungsional, serta bordir nama teknisi untuk tampilan profesional.',
    images: [
      'https://images.pexels.com/photos/3862601/pexels-photo-3862601.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/3862601/pexels-photo-3862601.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/1108101/pexels-photo-1108101.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 210000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 210000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 190000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 170000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Abu', hex: '#64748b' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 37,
    features: [
      'Bahan canvas tebal dan tahan lama',
      'Model coverall satu bagian',
      'Resleting YKK berkualitas',
      'Kantong banyak dan fungsional',
      'Bordir nama/logo perusahaan',
    ],
    specifications: [
      { label: 'Bahan', value: 'Canvas 280 gsm' },
      { label: 'Model', value: 'Coverall / Satu Bagian' },
      { label: 'Resleting', value: 'YKK' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '10–14 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },

  // ─── JAKET ────────────────────────────────────────────────────────────────
  {
    slug: 'jaket-varsity-premium',
    name: 'Jaket Varsity & Almamater',
    category: 'jaket',
    categoryLabel: 'Jaket',
    shortDescription: 'Jaket varsity dan almamater dengan kombinasi bahan premium.',
    description:
      'Jaket varsity dan almamater premium dengan kombinasi body wool premium dan sleeve kulit sintetis berkualitas. Lining furing lembut di dalam, kancing khas varsity, dan bordir logo yang elegan. Cocok untuk jaket wisuda, almamater, komunitas, dan organisasi.',
    images: [
      'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/8217420/pexels-photo-8217420.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/8217419/pexels-photo-8217419.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/2220316/pexels-photo-2220316.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 175000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 175000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 155000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 135000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Maroon', hex: '#7f1d1d' },
      { name: 'Forest', hex: '#14532d' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.9,
    reviewCount: 64,
    badge: 'Premium',
    features: [
      'Body wool premium 280 gsm, hangat dan ringan',
      'Sleeve kulit sintetis PU berkualitas',
      'Lining furing lembut di bagian dalam',
      'Kancing khas varsity logam',
      'Bordir logo computerized',
    ],
    specifications: [
      { label: 'Body', value: 'Wool Premium 280 gsm' },
      { label: 'Sleeve', value: 'Kulit Sintetis PU' },
      { label: 'Lining', value: 'Furing Premium' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '10–14 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },
  {
    slug: 'jaket-bomber',
    name: 'Jaket Bomber Custom',
    category: 'jaket',
    categoryLabel: 'Jaket',
    shortDescription: 'Jaket bomber custom dengan bahan taslan water repellent premium.',
    description:
      'Jaket bomber custom dengan bahan taslan yang water repellent (tahan air ringan) dan windproof. Lining furing fleece yang hangat. Cocok untuk seragam komunitas, kepanitiaan, event outdoor, dan promo brand.',
    images: [
      'https://images.pexels.com/photos/2220316/pexels-photo-2220316.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/8217420/pexels-photo-8217420.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/8217419/pexels-photo-8217419.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 155000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 155000, label: '10–49 pcs' },
      { minQty: 50, maxQty: 199, price: 135000, label: '50–199 pcs' },
      { minQty: 200, maxQty: null, price: 120000, label: '200+ pcs' },
    ],
    colors: [
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Olive', hex: '#3f6212' },
      { name: 'Abu', hex: '#64748b' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    rating: 4.8,
    reviewCount: 49,
    features: [
      'Bahan taslan water repellent & windproof',
      'Lining furing fleece hangat',
      'Resleting YKK berkualitas',
      'Bordir atau sablon logo',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Taslan Water Repellent' },
      { label: 'Lining', value: 'Fleece' },
      { label: 'Resleting', value: 'YKK' },
      { label: 'MOQ', value: '10 pcs' },
      { label: 'Estimasi Produksi', value: '10–14 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },

  // ─── BAHAN KAIN ───────────────────────────────────────────────────────────
  {
    slug: 'bahan-katun-combed',
    name: 'Bahan Katun Combed 30s',
    category: 'bahan-kain',
    categoryLabel: 'Bahan Kain',
    shortDescription: 'Kain katun combed 30s lembut, adem, dan berkualitas tinggi per meter.',
    description:
      'Kain katun combed 30s grade A yang lembut, adem, dan memiliki tekstur halus. Cocok untuk produksi kaos, baju tidur, dan pakaian casual. Tersedia berbagai warna solid dan motif. Dijual per meter dengan harga grosir.',
    images: [
      'https://images.pexels.com/photos/6809657/pexels-photo-6809657.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/6311387/pexels-photo-6311387.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/6809657/pexels-photo-6809657.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/6311387/pexels-photo-6311387.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 35000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 35000, label: '10–49 meter' },
      { minQty: 50, maxQty: 199, price: 30000, label: '50–199 meter' },
      { minQty: 200, maxQty: null, price: 27000, label: '200+ meter' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Maroon', hex: '#7f1d1d' },
    ],
    sizes: ['All Size'],
    rating: 4.9,
    reviewCount: 203,
    badge: 'Best Seller',
    features: [
      'Katun combed 30s grade A',
      'Lembut, adem, tekstur halus',
      'Tersedia 30+ pilihan warna',
      'Bisa request kain per roll',
      'Harga grosir langsung pabrik',
    ],
    specifications: [
      { label: 'Jenis', value: 'Katun Combed 30s' },
      { label: 'Tebal', value: '180 gsm' },
      { label: 'Lebar', value: '150–160 cm' },
      { label: 'Satuan', value: 'Per meter' },
      { label: 'Min. Pembelian', value: '10 meter' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },
  {
    slug: 'bahan-serge-drill',
    name: 'Bahan Serge & Drill Seragam',
    category: 'bahan-kain',
    categoryLabel: 'Bahan Kain',
    shortDescription: 'Kain serge dan drill untuk produksi seragam sekolah dan perusahaan.',
    description:
      'Kain serge dan drill berkualitas tinggi yang biasa digunakan untuk produksi seragam sekolah, seragam kantor, dan celana. Bahan tidak mudah kusut, tahan lama, dan memiliki jatuh yang bagus. Dijual per meter.',
    images: [
      'https://images.pexels.com/photos/6311387/pexels-photo-6311387.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/6809657/pexels-photo-6809657.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/6311387/pexels-photo-6311387.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/6809657/pexels-photo-6809657.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 28000,
    priceTiers: [
      { minQty: 10, maxQty: 49, price: 28000, label: '10–49 meter' },
      { minQty: 50, maxQty: 199, price: 24000, label: '50–199 meter' },
      { minQty: 200, maxQty: null, price: 21000, label: '200+ meter' },
    ],
    colors: [
      { name: 'Putih', hex: '#f8fafc' },
      { name: 'Abu', hex: '#64748b' },
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
    ],
    sizes: ['All Size'],
    rating: 4.8,
    reviewCount: 119,
    features: [
      'Serge & drill grade A',
      'Tidak mudah kusut, tahan lama',
      'Jatuh bagus untuk seragam',
      'Tersedia 20+ pilihan warna',
      'Harga grosir langsung pabrik',
    ],
    specifications: [
      { label: 'Jenis', value: 'Serge / Drill' },
      { label: 'Tebal', value: '200–220 gsm' },
      { label: 'Lebar', value: '150 cm' },
      { label: 'Satuan', value: 'Per meter' },
      { label: 'Min. Pembelian', value: '10 meter' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },

  // ─── ATRIBUT SEKOLAH ──────────────────────────────────────────────────────
  {
    slug: 'dasi-sekolah',
    name: 'Dasi Sekolah Custom',
    category: 'atribut-sekolah',
    categoryLabel: 'Atribut Sekolah',
    shortDescription: 'Dasi sekolah custom dengan warna dan logo sekolah sesuai permintaan.',
    description:
      'Dasi sekolah custom dengan bahan polyester satin berkualitas, warna dan corak sesuai identitas sekolah. Mudah dipakai dengan klip/karet pengait. Tersedia berbagai model: dasi panjang, kupu-kupu, dan segitiga.',
    images: [
      'https://images.pexels.com/photos/289737/pexels-photo-289737.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/8617715/pexels-photo-8617715.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/289737/pexels-photo-289737.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/8617742/pexels-photo-8617742.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 12000,
    priceTiers: [
      { minQty: 50, maxQty: 199, price: 12000, label: '50–199 pcs' },
      { minQty: 200, maxQty: 499, price: 10000, label: '200–499 pcs' },
      { minQty: 500, maxQty: null, price: 8500, label: '500+ pcs' },
    ],
    colors: [
      { name: 'Merah-Putih', hex: '#dc2626' },
      { name: 'Biru-Putih', hex: '#2563eb' },
      { name: 'Hijau-Putih', hex: '#16a34a' },
      { name: 'Kustom', hex: '#c9a84c' },
    ],
    sizes: ['All Size'],
    rating: 4.8,
    reviewCount: 156,
    badge: 'Populer',
    features: [
      'Bahan polyester satin berkualitas',
      'Warna dan corak kustom sesuai sekolah',
      'Mudah dipakai dengan klip pengait',
      'Tersedia model panjang, kupu-kupu, segitiga',
      'Tahan lama dan tidak mudah pudar',
    ],
    specifications: [
      { label: 'Bahan', value: 'Polyester Satin' },
      { label: 'Model', value: 'Panjang / Kupu-kupu / Segitiga' },
      { label: 'Pengait', value: 'Klip / Karet' },
      { label: 'MOQ', value: '50 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },
  {
    slug: 'topi-sekolah',
    name: 'Topi Sekolah Custom',
    category: 'atribut-sekolah',
    categoryLabel: 'Atribut Sekolah',
    shortDescription: 'Topi sekolah custom berbahan drill dengan bordir logo sekolah.',
    description:
      'Topi sekolah custom dengan bahan drill berkualitas yang tidak mudah layu. Bordir logo dan nama sekolah dengan computerized embroidery. Tersedia model topi pet (baseball cap), topi rimba, dan topi dinas sesuai kebutuhan sekolah.',
    images: [
      'https://images.pexels.com/photos/289737/pexels-photo-289737.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/8617743/pexels-photo-8617743.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/289737/pexels-photo-289737.jpeg?auto=compress&cs=tinysrgb&w=1200',
      'https://images.pexels.com/photos/8617715/pexels-photo-8617715.jpeg?auto=compress&cs=tinysrgb&w=1200',
    ],
    basePrice: 18000,
    priceTiers: [
      { minQty: 50, maxQty: 199, price: 18000, label: '50–199 pcs' },
      { minQty: 200, maxQty: 499, price: 15000, label: '200–499 pcs' },
      { minQty: 500, maxQty: null, price: 13000, label: '500+ pcs' },
    ],
    colors: [
      { name: 'Navy', hex: '#0a0a2e' },
      { name: 'Hitam', hex: '#0f172a' },
      { name: 'Abu', hex: '#64748b' },
      { name: 'Putih', hex: '#f8fafc' },
    ],
    sizes: ['All Size'],
    rating: 4.7,
    reviewCount: 98,
    features: [
      'Bahan drill berkualitas, tidak mudah layu',
      'Bordir logo sekolah computerized',
      'Tersedia model pet, rimba, dan dinas',
      'Ukuran adjustable',
      'Quality control ketat sebelum pengiriman',
    ],
    specifications: [
      { label: 'Bahan', value: 'Drill' },
      { label: 'Model', value: 'Pet / Rimba / Dinas' },
      { label: 'Teknik Logo', value: 'Computerized Embroidery' },
      { label: 'MOQ', value: '50 pcs' },
      { label: 'Estimasi Produksi', value: '5–7 hari kerja' },
      { label: 'Pengiriman', value: 'Seluruh Indonesia' },
    ],
    shopeeUrl: 'https://shopee.co.id/aguscollection',
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getProductsByCategory(categorySlug: string): Product[] {
  return products.filter((p) => p.category === categorySlug);
}
